apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnych-rolebinding
  namespace: kube-system
subjects:
- kind: User
  name: cnych 
  apiGroup: ""
roleRef:
  kind: Role 
  name: cnych-role
  apiGroup: ""