apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnych-role
  namespace: kube-system
rules:
- apiGroups: ["","apps"]
  resources: ["deployments", "pods","replicasets"]
  verbs: ["get", "list","watch","create"]