apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: cnych-sa-role
  namespace: kube-system 
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: ["apps"]
  resources: ["deployments","replicasets"]
  verbs: ["get","list","watch","create","update","patch","delete"]