apiVersion: v1 
kind: Service
metadata:
  name: etcd-k8s
  labels:
    k8s-app: etcd 
spec: 
  type: ClusterIP
  clusterIP: None 
  ports: 
  - name: port 
    port: 2379 

--- 
apiVersion: v1 
kind: Endpoints
metadata:
 name: etcd-k8s  #名称必须和service一致
 labels:
   k8s-app: etcd 
subsets:
- addresses:
  - ip: 10.151.30.57 #service将连接重定向到endpoint
  ports: 
  - name: port 
    port: 2379  #endpoint