apiVersion: v1 
kind: Service 
metadata: 
  name: myservice
spec:
  sessionAffinity: ClientIP # 会话亲和性
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: myapp-http