--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-deploy
  namespace: default
spec:
  replicas: 3  # 期望的 Pod 副本数量，默认值为1
  selector:  # Label Selector，必须匹配 Pod 模板中的标签
    matchLabels:
      app: nginx
  template:  # Pod 模板
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: ng 

--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: mysvc 
spec:
  selector: 
    app: nginx 
  type: NodePort 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: myapp-http 
