apiVersion: batch/v1
kind: CronJob 
metadata:
  name: cronjob-demo
spec: 
  schedule: "*/1 * * * *"
  jobTemplate:  #job模板
    spec:
     template:  #pod模板
       spec:
         restartPolicy: OnFailure
         containers:
         - name: hello
           image: busybox
           args:
           - "/bin/sh"
           - "-c"
           - "for i in 9 8 7 6 5 4 3 2 1; do echo $i; done"