workflow:
  rules:
    - if: $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"
      when: never
    - when: always

stages:
  - build 
  - test

variables:
  ENV_TYPE: "dev"
  GIT_CHECKOUT: "false" 

cibuild:
  tags:
    - build
  stage: build
  variables:
    GIT_CHECKOUT: "true" 
  script:
    - ls -l 
    - echo 123 >test.yaml 
    - ls -l 
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: '1 week'
    paths:
      - test.yaml

citest1:
  tags:
    - build
  stage: test
  script:
    - ls -l 
  dependencies:
    - cibuild 
