apiVersion: v1 
kind: Pod
metadata:
  name: container-sc-demo
  namespace: default
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: ["sh", "-c", "sleep 60m"]
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false